fos_elastica:
    clients:
        default: { host: %elasticsearch_server_url%, port: %elasticsearch_server_port% }
    indexes:
        app:
            types:
                index:
                    mappings:
                        id: {type: integer}
                        name:  { type: string, index: analyzed }
                        created_at: { type: date }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  App\Entity\Index
                        provider: ~
                        listener: ~
                        finder: ~